baseurl = "http://docs.getcloudify.org/"
languageCode = "en-us"
title = "XAP Documentation"
theme="hugo-bootswatch"
uglyurls=true

[permalinks]
    guide= "/3.3.0/:filename"

[params]
categoriescss= "/style/template.css"
highlightStyle="darkula"
sidebartitle = "Development"
sidebartagline = "Is super awesome"

xaplatestrelease="11.0"

projecturl="https://github.com/guy-mograbi-at-gigaspaces/getcloudify-hugo-version"
projectversion="3.1.0"


 

[[menu.social]]
    pre = "<i class='fa fa-twitter'></i>"
    url = "https://twitter.com/CloudifySource"
    identifier = "twitter"

[[menu.footer]]
    name = "Blog"
    url = "/posts"








SectionPagesMenu = "howto"




  