baseurl = "http://docs.getcloudify.org/"
languageCode = "en-us"
title = "XAP Documentation"
theme="hugo-bootswatch"
uglyurls=true

[params]
    xaplatestrelease="11.0"
    latestjavaurl="/xap110/"
    latestadmurl="/xap110adm/"
    latestsecurl="/xap110sec/"
    latestneturl="/xap110net/"



[[menu.footer]]
    name = "Blog"
    url = "/posts"

[[menu.xap100]]
    name = "Blog"
    url = "/xap110"












  