baseurl = "http://docs.getcloudify.org/"
languageCode = "en-us"
title = "XAP Documentation"
theme="hugo-bootswatch"
uglyurls=true

[params]
    xaplatestrelease="11.0"
    latestjavaurl="/xap110/"
    latestadmurl="/xap110adm/"
    latestsecurl="/xap110sec/"
    latestneturl="/xap110net/"




[[menu.footer]]
    name = "Blog"
    url = "/posts"

[[menu.xap100]]
    name = "Blog"
    url = "/xap110"


[params.xap102]
    java-version=         "8"

    spring=              "4.1"
    mongo-java-driver=    "2.11.2"
    antlr4-runtime=       "4.0"
    mule=                 "3.5"
    mongo-datasource=     "10.0.0-SNAPSHOT"
    openjpa=              "2.0.1"
    cassandra-clientutil= "1.1.6"
    cassandra-thrift=     "1.1.6"
    cassandra-jdbc=       "1.1.2"
    hector-core=          "1.1-2"
    slf4j-api=            "1.6.6"
    slf4j-jdk14=          "1.6.6"

    # Path and versions
    maven-version=        "10.2.0-13800-RELEASE"
    blobstore=            "blobstore-10.2.0-13800_RELEASE.noarch"
    gshome-directory=     "gigaspaces-xap-premium-10.2.0"
    default-lookup-group= "gigaspaces-10.2.0-XAPPremium-ga"
    build-filename=       "gigaspaces-xap-premium-10.2.0-ga-b13800.zip"
    xap-version=          "10.2"
    xap-release=          "10.2.0"

    # DOT NET
    msi-filename=          "GigaSpaces-XAP.NET-Premium-10.2.0.m-13800-x86.msi"
    gshome-net-directory=  "XAP.NET 10.2.0 x86"

 [params.xap110]
     java-version=         "8"

     spring=              "4.1"
     mongo-java-driver=    "2.11.2"
     antlr4-runtime=       "4.0"
     mule=                 "3.5"
     mongo-datasource=     "11.0.0-SNAPSHOT"
     openjpa=              "2.0.1"
     cassandra-clientutil= "1.1.6"
     cassandra-thrift=     "1.1.6"
     cassandra-jdbc=       "1.1.2"
     hector-core=          "1.1-2"
     slf4j-api=            "1.6.6"
     slf4j-jdk14=          "1.6.6"

     # Path and versions
     maven-version=        "11.0.0-13800-RELEASE"
     blobstore=            "blobstore-11.0.0-13800_RELEASE.noarch"
     gshome-directory=     "gigaspaces-xap-premium-11.0.0"
     default-lookup-group= "gigaspaces-11.0.0-XAPPremium-ga"
     build-filename=       "gigaspaces-xap-premium-11.0.0-ga-b13800.zip"
     xap-version=          "11.0"
     xap-release=          "11.0"

     # DOT NET
     msi-filename=          "GigaSpaces-XAP.NET-Premium-11.0.0.m-13800-x86.msi"
     gshome-net-directory=  "XAP.NET 11.0.0 x86"







  