baseurl = "http://docs.getcloudify.org/"
languageCode = "en-us"
title = "XAP Documentation"
theme="hugo-redlounge"
uglyurls=true

[permalinks]
    guide= "/3.3.0/:filename"

[params]
categoriescss= "/style/template.css"
highlightStyle="darkula"
sidebartitle = "Development"
sidebartagline = "Is super awesome"

[params.xap]
xaplatestrelease="10.2"

projecturl="https://github.com/guy-mograbi-at-gigaspaces/getcloudify-hugo-version"
projectversion="3.1.0"


[[menu.main]]
    name = "Blog"
    url = "/posts"

[[menu.social]]
    pre = "<i class='fa fa-twitter'></i>"
    url = "https://twitter.com/CloudifySource"
    identifier = "twitter"

[[menu.footer]]
    name = "Blog"
    url = "/posts"
